language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t omraj/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run omraj/react-test npm test -- --coverage

after_success:
  - docker build -t omraj/multi-client ./client
  - docker build -t omraj/multi-nginx ./nginx
  - docker build -t omraj/multi-server ./server
  - docker build -t omraj/multi-worker ./worker
  #Login in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those image and push them to docker hub
  - docker push omraj/multi-client
  - docker push omraj/multi-nginx
  - docker push omraj/multi-server
  - docker push omraj/multi-worker